name: Deploy

on:
 push:
   branches: [main]

permissions:
 id-token: write
 contents: read

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v4
     with:
       fetch-depth: 0

   - uses: actions/setup-node@v4
     with:
       node-version: 20
       cache: npm

   - run: npm install
   - run: npm run build

   - uses: aws-actions/configure-aws-credentials@v4
     with:
       role-to-assume: arn:aws:iam::841203434308:role/LabRole
       aws-region: us-east-1

   - run: aws s3 sync dist/ s3://myapp-1773052638/ --delete
